const survivorData = {
  "HasWinner": false,
  "WinnerName": null,
  "Pickers": [
    {
      "Name": "Zach A",
      "Eliminated": false,
      "WeekEliminated": null,
      "EliminationReason": null,
      "Picks": [
        {
          "PickDateTime": "2022-09-16T00:30:51",
          "Name": "Zach A",
          "Week": 3,
          "Team": "Michigan",
          "Correct": true,
          "SelectionStatus": "Beat UConn 59-0"
        },
        {
          "PickDateTime": "2022-09-24T17:57:09",
          "Name": "Zach A",
          "Week": 4,
          "Team": "Ohio State",
          "Correct": true,
          "SelectionStatus": "Beat Wisconsin 52-21"
        }
      ],
      "AllNames": [
        "zacha"
      ]
    },
    {
      "Name": "Gools",
      "Eliminated": true,
      "WeekEliminated": 4,
      "EliminationReason": "Incorrect Pick: Illinois",
      "Picks": [
        {
          "PickDateTime": "2022-09-16T00:48:37",
          "Name": "Gools",
          "Week": 3,
          "Team": "Rutgers",
          "Correct": true,
          "SelectionStatus": "Beat Temple 16-14"
        },
        {
          "PickDateTime": "2022-09-24T11:20:32",
          "Name": "Gools",
          "Week": 4,
          "Team": "Illinois",
          "Correct": false,
          "SelectionStatus": "Late Pick"
        }
      ],
      "AllNames": [
        "gools"
      ]
    },
    {
      "Name": "Beast",
      "Eliminated": true,
      "WeekEliminated": 4,
      "EliminationReason": "No Pick",
      "Picks": [
        {
          "PickDateTime": "2022-09-16T08:32:13",
          "Name": "Beast",
          "Week": 3,
          "Team": "Wisconsin",
          "Correct": true,
          "SelectionStatus": "Beat New Mexico State 66-7"
        }
      ],
      "AllNames": [
        "beast"
      ]
    },
    {
      "Name": "Woody",
      "Eliminated": false,
      "WeekEliminated": null,
      "EliminationReason": null,
      "Picks": [
        {
          "PickDateTime": "2022-09-16T21:57:19",
          "Name": "Woody",
          "Week": 3,
          "Team": "Wisconsin",
          "Correct": true,
          "SelectionStatus": "Beat New Mexico State 66-7"
        },
        {
          "PickDateTime": "2022-09-24T11:00:46",
          "Name": "Woody",
          "Week": 4,
          "Team": "Penn State",
          "Correct": true,
          "SelectionStatus": "Beat Central Michigan 33-14"
        }
      ],
      "AllNames": [
        "woody"
      ]
    },
    {
      "Name": "Drew",
      "Eliminated": false,
      "WeekEliminated": null,
      "EliminationReason": null,
      "Picks": [
        {
          "PickDateTime": "2022-09-16T23:48:02",
          "Name": "Drew",
          "Week": 3,
          "Team": "Wisconsin",
          "Correct": true,
          "SelectionStatus": "Beat New Mexico State 66-7"
        },
        {
          "PickDateTime": "2022-09-24T11:08:44",
          "Name": "Drew",
          "Week": 4,
          "Team": "Penn State",
          "Correct": true,
          "SelectionStatus": "Beat Central Michigan 33-14"
        }
      ],
      "AllNames": [
        "drew"
      ]
    },
    {
      "Name": "Ronnie",
      "Eliminated": false,
      "WeekEliminated": null,
      "EliminationReason": null,
      "Picks": [
        {
          "PickDateTime": "2022-09-17T09:33:56",
          "Name": "Ronnie",
          "Week": 3,
          "Team": "Wisconsin",
          "Correct": true,
          "SelectionStatus": "Beat New Mexico State 66-7"
        },
        {
          "PickDateTime": "2022-09-24T14:41:58",
          "Name": "Ronnie Shoemaker",
          "Week": 4,
          "Team": "Purdue",
          "Correct": true,
          "SelectionStatus": "Beat Florida Atlantic 28-26"
        }
      ],
      "AllNames": [
        "ronnie",
        "ronnieshoemaker"
      ]
    },
    {
      "Name": "8",
      "Eliminated": false,
      "WeekEliminated": null,
      "EliminationReason": null,
      "Picks": [
        {
          "PickDateTime": "2022-09-17T13:13:13",
          "Name": "8",
          "Week": 3,
          "Team": "Minnesota",
          "Correct": true,
          "SelectionStatus": "Beat Colorado 49-7"
        },
        {
          "PickDateTime": "2022-09-23T13:43:16",
          "Name": "8",
          "Week": 4,
          "Team": "Purdue",
          "Correct": true,
          "SelectionStatus": "Beat Florida Atlantic 28-26"
        }
      ],
      "AllNames": [
        "8"
      ]
    },
    {
      "Name": "Dan",
      "Eliminated": false,
      "WeekEliminated": null,
      "EliminationReason": null,
      "Picks": [
        {
          "PickDateTime": "2022-09-17T13:19:35",
          "Name": "Dan",
          "Week": 3,
          "Team": "Minnesota",
          "Correct": true,
          "SelectionStatus": "Beat Colorado 49-7"
        },
        {
          "PickDateTime": "2022-09-21T13:14:09",
          "Name": "Dan",
          "Week": 4,
          "Team": "Illinois",
          "Correct": true,
          "SelectionStatus": "Beat Chattanooga 31-0"
        }
      ],
      "AllNames": [
        "dan"
      ]
    },
    {
      "Name": "Jeff",
      "Eliminated": false,
      "WeekEliminated": null,
      "EliminationReason": null,
      "Picks": [
        {
          "PickDateTime": "2022-09-17T13:36:16",
          "Name": "Jeff",
          "Week": 3,
          "Team": "Iowa",
          "Correct": true,
          "SelectionStatus": "Beat Nevada 27-0"
        },
        {
          "PickDateTime": "2022-09-24T12:30:33",
          "Name": "Jeff",
          "Week": 4,
          "Team": "Purdue",
          "Correct": true,
          "SelectionStatus": "Beat Florida Atlantic 28-26"
        }
      ],
      "AllNames": [
        "jeff"
      ]
    },
    {
      "Name": "Bob",
      "Eliminated": true,
      "WeekEliminated": 3,
      "EliminationReason": "Incorrect Pick: Ohio State",
      "Picks": [
        {
          "PickDateTime": "2022-09-18T12:27:37",
          "Name": "Bob",
          "Week": 3,
          "Team": "Ohio State",
          "Correct": false,
          "SelectionStatus": "Late Pick"
        }
      ],
      "AllNames": [
        "bob"
      ]
    }
  ],
  "Schedule": [
    {
      "WeekNum": 3,
      "StartDate": "2022-09-13T03:00:00-04:00",
      "EndDate": "2022-09-20T02:59:00-04:00",
      "Games": [
        {
          "FullName": "Ohio State Buckeyes",
          "Location": "Ohio State",
          "Abbreviation": "OSU",
          "Week": 3,
          "Winner": true,
          "HomeTeam": true,
          "OpponentLocation": "Toledo",
          "Score": "77-21",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-17T19:00:00-04:00"
        },
        {
          "FullName": "Michigan Wolverines",
          "Location": "Michigan",
          "Abbreviation": "MICH",
          "Week": 3,
          "Winner": true,
          "HomeTeam": true,
          "OpponentLocation": "UConn",
          "Score": "59-0",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-17T12:00:00-04:00"
        },
        {
          "FullName": "Nebraska Cornhuskers",
          "Location": "Nebraska",
          "Abbreviation": "NEB",
          "Week": 3,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Oklahoma",
          "Score": "14-49",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-17T12:00:00-04:00"
        },
        {
          "FullName": "Michigan State Spartans",
          "Location": "Michigan State",
          "Abbreviation": "MSU",
          "Week": 3,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Washington",
          "Score": "28-39",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-17T19:30:00-04:00"
        },
        {
          "FullName": "Penn State Nittany Lions",
          "Location": "Penn State",
          "Abbreviation": "PSU",
          "Week": 3,
          "Winner": true,
          "HomeTeam": false,
          "OpponentLocation": "Auburn",
          "Score": "41-12",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-17T15:30:00-04:00"
        },
        {
          "FullName": "Northwestern Wildcats",
          "Location": "Northwestern",
          "Abbreviation": "NU",
          "Week": 3,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Southern Illinois",
          "Score": "24-31",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-17T12:00:00-04:00"
        },
        {
          "FullName": "Purdue Boilermakers",
          "Location": "Purdue",
          "Abbreviation": "PUR",
          "Week": 3,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Syracuse",
          "Score": "29-32",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-17T12:00:00-04:00"
        },
        {
          "FullName": "Indiana Hoosiers",
          "Location": "Indiana",
          "Abbreviation": "IU",
          "Week": 3,
          "Winner": true,
          "HomeTeam": true,
          "OpponentLocation": "Western Kentucky",
          "Score": "33-30",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-17T12:00:00-04:00"
        },
        {
          "FullName": "Rutgers Scarlet Knights",
          "Location": "Rutgers",
          "Abbreviation": "RUTG",
          "Week": 3,
          "Winner": true,
          "HomeTeam": false,
          "OpponentLocation": "Temple",
          "Score": "16-14",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-17T14:00:00-04:00"
        },
        {
          "FullName": "Minnesota Golden Gophers",
          "Location": "Minnesota",
          "Abbreviation": "MINN",
          "Week": 3,
          "Winner": true,
          "HomeTeam": true,
          "OpponentLocation": "Colorado",
          "Score": "49-7",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-17T15:30:00-04:00"
        },
        {
          "FullName": "Wisconsin Badgers",
          "Location": "Wisconsin",
          "Abbreviation": "WISC",
          "Week": 3,
          "Winner": true,
          "HomeTeam": true,
          "OpponentLocation": "New Mexico State",
          "Score": "66-7",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-17T15:30:00-04:00"
        },
        {
          "FullName": "Iowa Hawkeyes",
          "Location": "Iowa",
          "Abbreviation": "IOWA",
          "Week": 3,
          "Winner": true,
          "HomeTeam": true,
          "OpponentLocation": "Nevada",
          "Score": "27-0",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-17T19:30:00-04:00"
        },
        {
          "FullName": "Maryland Terrapins",
          "Location": "Maryland",
          "Abbreviation": "MD",
          "Week": 3,
          "Winner": true,
          "HomeTeam": true,
          "OpponentLocation": "SMU",
          "Score": "34-27",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-17T19:30:00-04:00"
        }
      ]
    },
    {
      "WeekNum": 4,
      "StartDate": "2022-09-20T03:00:00-04:00",
      "EndDate": "2022-09-27T02:59:00-04:00",
      "Games": [
        {
          "FullName": "Illinois Fighting Illini",
          "Location": "Illinois",
          "Abbreviation": "ILL",
          "Week": 4,
          "Winner": true,
          "HomeTeam": true,
          "OpponentLocation": "Chattanooga",
          "Score": "31-0",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-22T20:30:00-04:00"
        },
        {
          "FullName": "Ohio State Buckeyes",
          "Location": "Ohio State",
          "Abbreviation": "OSU",
          "Week": 4,
          "Winner": true,
          "HomeTeam": true,
          "OpponentLocation": "Wisconsin",
          "Score": "52-21",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-24T19:30:00-04:00"
        },
        {
          "FullName": "Wisconsin Badgers",
          "Location": "Wisconsin",
          "Abbreviation": "WISC",
          "Week": 4,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Ohio State",
          "Score": "21-52",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-24T19:30:00-04:00"
        },
        {
          "FullName": "Michigan Wolverines",
          "Location": "Michigan",
          "Abbreviation": "MICH",
          "Week": 4,
          "Winner": true,
          "HomeTeam": true,
          "OpponentLocation": "Maryland",
          "Score": "34-27",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-24T12:00:00-04:00"
        },
        {
          "FullName": "Maryland Terrapins",
          "Location": "Maryland",
          "Abbreviation": "MD",
          "Week": 4,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Michigan",
          "Score": "27-34",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-24T12:00:00-04:00"
        },
        {
          "FullName": "Penn State Nittany Lions",
          "Location": "Penn State",
          "Abbreviation": "PSU",
          "Week": 4,
          "Winner": true,
          "HomeTeam": true,
          "OpponentLocation": "Central Michigan",
          "Score": "33-14",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-24T12:00:00-04:00"
        },
        {
          "FullName": "Michigan State Spartans",
          "Location": "Michigan State",
          "Abbreviation": "MSU",
          "Week": 4,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Minnesota",
          "Score": "7-34",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-24T15:30:00-04:00"
        },
        {
          "FullName": "Minnesota Golden Gophers",
          "Location": "Minnesota",
          "Abbreviation": "MINN",
          "Week": 4,
          "Winner": true,
          "HomeTeam": false,
          "OpponentLocation": "Michigan State",
          "Score": "34-7",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-24T15:30:00-04:00"
        },
        {
          "FullName": "Indiana Hoosiers",
          "Location": "Indiana",
          "Abbreviation": "IU",
          "Week": 4,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Cincinnati",
          "Score": "24-45",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-24T15:30:00-04:00"
        },
        {
          "FullName": "Rutgers Scarlet Knights",
          "Location": "Rutgers",
          "Abbreviation": "RUTG",
          "Week": 4,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Iowa",
          "Score": "10-27",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-24T19:00:00-04:00"
        },
        {
          "FullName": "Iowa Hawkeyes",
          "Location": "Iowa",
          "Abbreviation": "IOWA",
          "Week": 4,
          "Winner": true,
          "HomeTeam": false,
          "OpponentLocation": "Rutgers",
          "Score": "27-10",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-24T19:00:00-04:00"
        },
        {
          "FullName": "Northwestern Wildcats",
          "Location": "Northwestern",
          "Abbreviation": "NU",
          "Week": 4,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Miami (OH)",
          "Score": "14-17",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-24T19:30:00-04:00"
        },
        {
          "FullName": "Purdue Boilermakers",
          "Location": "Purdue",
          "Abbreviation": "PUR",
          "Week": 4,
          "Winner": true,
          "HomeTeam": true,
          "OpponentLocation": "Florida Atlantic",
          "Score": "28-26",
          "IsBigTen": true,
          "IsCompleted": true,
          "GameDateTime": "2022-09-24T19:30:00-04:00"
        }
      ]
    },
    {
      "WeekNum": 5,
      "StartDate": "2022-09-27T03:00:00-04:00",
      "EndDate": "2022-10-04T02:59:00-04:00",
      "Games": [
        {
          "FullName": "Iowa Hawkeyes",
          "Location": "Iowa",
          "Abbreviation": "IOWA",
          "Week": 5,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Michigan",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-01T12:00:00-04:00"
        },
        {
          "FullName": "Michigan Wolverines",
          "Location": "Michigan",
          "Abbreviation": "MICH",
          "Week": 5,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Iowa",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-01T12:00:00-04:00"
        },
        {
          "FullName": "Minnesota Golden Gophers",
          "Location": "Minnesota",
          "Abbreviation": "MINN",
          "Week": 5,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Purdue",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-01T12:00:00-04:00"
        },
        {
          "FullName": "Purdue Boilermakers",
          "Location": "Purdue",
          "Abbreviation": "PUR",
          "Week": 5,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Minnesota",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-01T12:00:00-04:00"
        },
        {
          "FullName": "Wisconsin Badgers",
          "Location": "Wisconsin",
          "Abbreviation": "WISC",
          "Week": 5,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Illinois",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-01T12:00:00-04:00"
        },
        {
          "FullName": "Illinois Fighting Illini",
          "Location": "Illinois",
          "Abbreviation": "ILL",
          "Week": 5,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Wisconsin",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-01T12:00:00-04:00"
        },
        {
          "FullName": "Ohio State Buckeyes",
          "Location": "Ohio State",
          "Abbreviation": "OSU",
          "Week": 5,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Rutgers",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-01T15:30:00-04:00"
        },
        {
          "FullName": "Rutgers Scarlet Knights",
          "Location": "Rutgers",
          "Abbreviation": "RUTG",
          "Week": 5,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Ohio State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-01T15:30:00-04:00"
        },
        {
          "FullName": "Penn State Nittany Lions",
          "Location": "Penn State",
          "Abbreviation": "PSU",
          "Week": 5,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Northwestern",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-01T15:30:00-04:00"
        },
        {
          "FullName": "Northwestern Wildcats",
          "Location": "Northwestern",
          "Abbreviation": "NU",
          "Week": 5,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Penn State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-01T15:30:00-04:00"
        },
        {
          "FullName": "Maryland Terrapins",
          "Location": "Maryland",
          "Abbreviation": "MD",
          "Week": 5,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Michigan State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-01T15:30:00-04:00"
        },
        {
          "FullName": "Michigan State Spartans",
          "Location": "Michigan State",
          "Abbreviation": "MSU",
          "Week": 5,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Maryland",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-01T15:30:00-04:00"
        },
        {
          "FullName": "Nebraska Cornhuskers",
          "Location": "Nebraska",
          "Abbreviation": "NEB",
          "Week": 5,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Indiana",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-01T19:30:00-04:00"
        },
        {
          "FullName": "Indiana Hoosiers",
          "Location": "Indiana",
          "Abbreviation": "IU",
          "Week": 5,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Nebraska",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-01T19:30:00-04:00"
        }
      ]
    },
    {
      "WeekNum": 6,
      "StartDate": "2022-10-04T03:00:00-04:00",
      "EndDate": "2022-10-11T02:59:00-04:00",
      "Games": [
        {
          "FullName": "Rutgers Scarlet Knights",
          "Location": "Rutgers",
          "Abbreviation": "RUTG",
          "Week": 6,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Nebraska",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-07T19:00:00-04:00"
        },
        {
          "FullName": "Nebraska Cornhuskers",
          "Location": "Nebraska",
          "Abbreviation": "NEB",
          "Week": 6,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Rutgers",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-07T19:00:00-04:00"
        },
        {
          "FullName": "Illinois Fighting Illini",
          "Location": "Illinois",
          "Abbreviation": "ILL",
          "Week": 6,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Iowa",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-08T00:00:00-04:00"
        },
        {
          "FullName": "Iowa Hawkeyes",
          "Location": "Iowa",
          "Abbreviation": "IOWA",
          "Week": 6,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Illinois",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-08T00:00:00-04:00"
        },
        {
          "FullName": "Northwestern Wildcats",
          "Location": "Northwestern",
          "Abbreviation": "NU",
          "Week": 6,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Wisconsin",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-08T00:00:00-04:00"
        },
        {
          "FullName": "Wisconsin Badgers",
          "Location": "Wisconsin",
          "Abbreviation": "WISC",
          "Week": 6,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Northwestern",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-08T00:00:00-04:00"
        },
        {
          "FullName": "Indiana Hoosiers",
          "Location": "Indiana",
          "Abbreviation": "IU",
          "Week": 6,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Michigan",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-08T12:00:00-04:00"
        },
        {
          "FullName": "Michigan Wolverines",
          "Location": "Michigan",
          "Abbreviation": "MICH",
          "Week": 6,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Indiana",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-08T12:00:00-04:00"
        },
        {
          "FullName": "Maryland Terrapins",
          "Location": "Maryland",
          "Abbreviation": "MD",
          "Week": 6,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Purdue",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-08T12:00:00-04:00"
        },
        {
          "FullName": "Purdue Boilermakers",
          "Location": "Purdue",
          "Abbreviation": "PUR",
          "Week": 6,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Maryland",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-08T12:00:00-04:00"
        },
        {
          "FullName": "Michigan State Spartans",
          "Location": "Michigan State",
          "Abbreviation": "MSU",
          "Week": 6,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Ohio State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-08T16:00:00-04:00"
        },
        {
          "FullName": "Ohio State Buckeyes",
          "Location": "Ohio State",
          "Abbreviation": "OSU",
          "Week": 6,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Michigan State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-08T16:00:00-04:00"
        }
      ]
    },
    {
      "WeekNum": 7,
      "StartDate": "2022-10-11T03:00:00-04:00",
      "EndDate": "2022-10-18T02:59:00-04:00",
      "Games": [
        {
          "FullName": "Michigan Wolverines",
          "Location": "Michigan",
          "Abbreviation": "MICH",
          "Week": 7,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Penn State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-15T00:00:00-04:00"
        },
        {
          "FullName": "Penn State Nittany Lions",
          "Location": "Penn State",
          "Abbreviation": "PSU",
          "Week": 7,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Michigan",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-15T00:00:00-04:00"
        },
        {
          "FullName": "Purdue Boilermakers",
          "Location": "Purdue",
          "Abbreviation": "PUR",
          "Week": 7,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Nebraska",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-15T00:00:00-04:00"
        },
        {
          "FullName": "Nebraska Cornhuskers",
          "Location": "Nebraska",
          "Abbreviation": "NEB",
          "Week": 7,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Purdue",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-15T00:00:00-04:00"
        },
        {
          "FullName": "Indiana Hoosiers",
          "Location": "Indiana",
          "Abbreviation": "IU",
          "Week": 7,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Maryland",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-15T00:00:00-04:00"
        },
        {
          "FullName": "Maryland Terrapins",
          "Location": "Maryland",
          "Abbreviation": "MD",
          "Week": 7,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Indiana",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-15T00:00:00-04:00"
        },
        {
          "FullName": "Michigan State Spartans",
          "Location": "Michigan State",
          "Abbreviation": "MSU",
          "Week": 7,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Wisconsin",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-15T00:00:00-04:00"
        },
        {
          "FullName": "Wisconsin Badgers",
          "Location": "Wisconsin",
          "Abbreviation": "WISC",
          "Week": 7,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Michigan State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-15T00:00:00-04:00"
        },
        {
          "FullName": "Illinois Fighting Illini",
          "Location": "Illinois",
          "Abbreviation": "ILL",
          "Week": 7,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Minnesota",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-15T12:00:00-04:00"
        },
        {
          "FullName": "Minnesota Golden Gophers",
          "Location": "Minnesota",
          "Abbreviation": "MINN",
          "Week": 7,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Illinois",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-15T12:00:00-04:00"
        }
      ]
    },
    {
      "WeekNum": 8,
      "StartDate": "2022-10-18T03:00:00-04:00",
      "EndDate": "2022-10-25T02:59:00-04:00",
      "Games": [
        {
          "FullName": "Ohio State Buckeyes",
          "Location": "Ohio State",
          "Abbreviation": "OSU",
          "Week": 8,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Iowa",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-22T00:00:00-04:00"
        },
        {
          "FullName": "Iowa Hawkeyes",
          "Location": "Iowa",
          "Abbreviation": "IOWA",
          "Week": 8,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Ohio State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-22T00:00:00-04:00"
        },
        {
          "FullName": "Rutgers Scarlet Knights",
          "Location": "Rutgers",
          "Abbreviation": "RUTG",
          "Week": 8,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Indiana",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-22T12:00:00-04:00"
        },
        {
          "FullName": "Indiana Hoosiers",
          "Location": "Indiana",
          "Abbreviation": "IU",
          "Week": 8,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Rutgers",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-22T12:00:00-04:00"
        },
        {
          "FullName": "Wisconsin Badgers",
          "Location": "Wisconsin",
          "Abbreviation": "WISC",
          "Week": 8,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Purdue",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-22T15:30:00-04:00"
        },
        {
          "FullName": "Purdue Boilermakers",
          "Location": "Purdue",
          "Abbreviation": "PUR",
          "Week": 8,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Wisconsin",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-22T15:30:00-04:00"
        },
        {
          "FullName": "Maryland Terrapins",
          "Location": "Maryland",
          "Abbreviation": "MD",
          "Week": 8,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Northwestern",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-22T15:30:00-04:00"
        },
        {
          "FullName": "Northwestern Wildcats",
          "Location": "Northwestern",
          "Abbreviation": "NU",
          "Week": 8,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Maryland",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-22T15:30:00-04:00"
        },
        {
          "FullName": "Penn State Nittany Lions",
          "Location": "Penn State",
          "Abbreviation": "PSU",
          "Week": 8,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Minnesota",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-22T19:30:00-04:00"
        },
        {
          "FullName": "Minnesota Golden Gophers",
          "Location": "Minnesota",
          "Abbreviation": "MINN",
          "Week": 8,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Penn State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-22T19:30:00-04:00"
        }
      ]
    },
    {
      "WeekNum": 9,
      "StartDate": "2022-10-25T03:00:00-04:00",
      "EndDate": "2022-11-01T02:59:00-04:00",
      "Games": [
        {
          "FullName": "Penn State Nittany Lions",
          "Location": "Penn State",
          "Abbreviation": "PSU",
          "Week": 9,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Ohio State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-29T00:00:00-04:00"
        },
        {
          "FullName": "Ohio State Buckeyes",
          "Location": "Ohio State",
          "Abbreviation": "OSU",
          "Week": 9,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Penn State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-29T00:00:00-04:00"
        },
        {
          "FullName": "Michigan Wolverines",
          "Location": "Michigan",
          "Abbreviation": "MICH",
          "Week": 9,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Michigan State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-29T00:00:00-04:00"
        },
        {
          "FullName": "Michigan State Spartans",
          "Location": "Michigan State",
          "Abbreviation": "MSU",
          "Week": 9,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Michigan",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-29T00:00:00-04:00"
        },
        {
          "FullName": "Minnesota Golden Gophers",
          "Location": "Minnesota",
          "Abbreviation": "MINN",
          "Week": 9,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Rutgers",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-29T00:00:00-04:00"
        },
        {
          "FullName": "Rutgers Scarlet Knights",
          "Location": "Rutgers",
          "Abbreviation": "RUTG",
          "Week": 9,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Minnesota",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-29T00:00:00-04:00"
        },
        {
          "FullName": "Nebraska Cornhuskers",
          "Location": "Nebraska",
          "Abbreviation": "NEB",
          "Week": 9,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Illinois",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-29T00:00:00-04:00"
        },
        {
          "FullName": "Illinois Fighting Illini",
          "Location": "Illinois",
          "Abbreviation": "ILL",
          "Week": 9,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Nebraska",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-29T00:00:00-04:00"
        },
        {
          "FullName": "Iowa Hawkeyes",
          "Location": "Iowa",
          "Abbreviation": "IOWA",
          "Week": 9,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Northwestern",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-29T15:00:00-04:00"
        },
        {
          "FullName": "Northwestern Wildcats",
          "Location": "Northwestern",
          "Abbreviation": "NU",
          "Week": 9,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Iowa",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-10-29T15:00:00-04:00"
        }
      ]
    },
    {
      "WeekNum": 10,
      "StartDate": "2022-11-01T03:00:00-04:00",
      "EndDate": "2022-11-08T02:59:00-05:00",
      "Games": [
        {
          "FullName": "Northwestern Wildcats",
          "Location": "Northwestern",
          "Abbreviation": "NU",
          "Week": 10,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Ohio State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-05T00:00:00-04:00"
        },
        {
          "FullName": "Ohio State Buckeyes",
          "Location": "Ohio State",
          "Abbreviation": "OSU",
          "Week": 10,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Northwestern",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-05T00:00:00-04:00"
        },
        {
          "FullName": "Rutgers Scarlet Knights",
          "Location": "Rutgers",
          "Abbreviation": "RUTG",
          "Week": 10,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Michigan",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-05T00:00:00-04:00"
        },
        {
          "FullName": "Michigan Wolverines",
          "Location": "Michigan",
          "Abbreviation": "MICH",
          "Week": 10,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Rutgers",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-05T00:00:00-04:00"
        },
        {
          "FullName": "Indiana Hoosiers",
          "Location": "Indiana",
          "Abbreviation": "IU",
          "Week": 10,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Penn State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-05T00:00:00-04:00"
        },
        {
          "FullName": "Penn State Nittany Lions",
          "Location": "Penn State",
          "Abbreviation": "PSU",
          "Week": 10,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Indiana",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-05T00:00:00-04:00"
        },
        {
          "FullName": "Nebraska Cornhuskers",
          "Location": "Nebraska",
          "Abbreviation": "NEB",
          "Week": 10,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Minnesota",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-05T00:00:00-04:00"
        },
        {
          "FullName": "Minnesota Golden Gophers",
          "Location": "Minnesota",
          "Abbreviation": "MINN",
          "Week": 10,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Nebraska",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-05T00:00:00-04:00"
        },
        {
          "FullName": "Illinois Fighting Illini",
          "Location": "Illinois",
          "Abbreviation": "ILL",
          "Week": 10,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Michigan State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-05T00:00:00-04:00"
        },
        {
          "FullName": "Michigan State Spartans",
          "Location": "Michigan State",
          "Abbreviation": "MSU",
          "Week": 10,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Illinois",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-05T00:00:00-04:00"
        },
        {
          "FullName": "Purdue Boilermakers",
          "Location": "Purdue",
          "Abbreviation": "PUR",
          "Week": 10,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Iowa",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-05T00:00:00-04:00"
        },
        {
          "FullName": "Iowa Hawkeyes",
          "Location": "Iowa",
          "Abbreviation": "IOWA",
          "Week": 10,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Purdue",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-05T00:00:00-04:00"
        },
        {
          "FullName": "Wisconsin Badgers",
          "Location": "Wisconsin",
          "Abbreviation": "WISC",
          "Week": 10,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Maryland",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-05T00:00:00-04:00"
        },
        {
          "FullName": "Maryland Terrapins",
          "Location": "Maryland",
          "Abbreviation": "MD",
          "Week": 10,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Wisconsin",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-05T00:00:00-04:00"
        }
      ]
    },
    {
      "WeekNum": 11,
      "StartDate": "2022-11-08T03:00:00-05:00",
      "EndDate": "2022-11-15T02:59:00-05:00",
      "Games": [
        {
          "FullName": "Ohio State Buckeyes",
          "Location": "Ohio State",
          "Abbreviation": "OSU",
          "Week": 11,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Indiana",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-12T00:00:00-05:00"
        },
        {
          "FullName": "Indiana Hoosiers",
          "Location": "Indiana",
          "Abbreviation": "IU",
          "Week": 11,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Ohio State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-12T00:00:00-05:00"
        },
        {
          "FullName": "Michigan Wolverines",
          "Location": "Michigan",
          "Abbreviation": "MICH",
          "Week": 11,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Nebraska",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-12T00:00:00-05:00"
        },
        {
          "FullName": "Nebraska Cornhuskers",
          "Location": "Nebraska",
          "Abbreviation": "NEB",
          "Week": 11,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Michigan",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-12T00:00:00-05:00"
        },
        {
          "FullName": "Penn State Nittany Lions",
          "Location": "Penn State",
          "Abbreviation": "PSU",
          "Week": 11,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Maryland",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-12T00:00:00-05:00"
        },
        {
          "FullName": "Maryland Terrapins",
          "Location": "Maryland",
          "Abbreviation": "MD",
          "Week": 11,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Penn State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-12T00:00:00-05:00"
        },
        {
          "FullName": "Minnesota Golden Gophers",
          "Location": "Minnesota",
          "Abbreviation": "MINN",
          "Week": 11,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Northwestern",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-12T00:00:00-05:00"
        },
        {
          "FullName": "Northwestern Wildcats",
          "Location": "Northwestern",
          "Abbreviation": "NU",
          "Week": 11,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Minnesota",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-12T00:00:00-05:00"
        },
        {
          "FullName": "Illinois Fighting Illini",
          "Location": "Illinois",
          "Abbreviation": "ILL",
          "Week": 11,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Purdue",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-12T00:00:00-05:00"
        },
        {
          "FullName": "Purdue Boilermakers",
          "Location": "Purdue",
          "Abbreviation": "PUR",
          "Week": 11,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Illinois",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-12T00:00:00-05:00"
        },
        {
          "FullName": "Iowa Hawkeyes",
          "Location": "Iowa",
          "Abbreviation": "IOWA",
          "Week": 11,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Wisconsin",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-12T00:00:00-05:00"
        },
        {
          "FullName": "Wisconsin Badgers",
          "Location": "Wisconsin",
          "Abbreviation": "WISC",
          "Week": 11,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Iowa",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-12T00:00:00-05:00"
        },
        {
          "FullName": "Michigan State Spartans",
          "Location": "Michigan State",
          "Abbreviation": "MSU",
          "Week": 11,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Rutgers",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-12T00:00:00-05:00"
        },
        {
          "FullName": "Rutgers Scarlet Knights",
          "Location": "Rutgers",
          "Abbreviation": "RUTG",
          "Week": 11,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Michigan State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-12T00:00:00-05:00"
        }
      ]
    },
    {
      "WeekNum": 12,
      "StartDate": "2022-11-15T03:00:00-05:00",
      "EndDate": "2022-11-22T02:59:00-05:00",
      "Games": [
        {
          "FullName": "Maryland Terrapins",
          "Location": "Maryland",
          "Abbreviation": "MD",
          "Week": 12,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Ohio State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-19T00:00:00-05:00"
        },
        {
          "FullName": "Ohio State Buckeyes",
          "Location": "Ohio State",
          "Abbreviation": "OSU",
          "Week": 12,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Maryland",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-19T00:00:00-05:00"
        },
        {
          "FullName": "Michigan Wolverines",
          "Location": "Michigan",
          "Abbreviation": "MICH",
          "Week": 12,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Illinois",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-19T00:00:00-05:00"
        },
        {
          "FullName": "Illinois Fighting Illini",
          "Location": "Illinois",
          "Abbreviation": "ILL",
          "Week": 12,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Michigan",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-19T00:00:00-05:00"
        },
        {
          "FullName": "Rutgers Scarlet Knights",
          "Location": "Rutgers",
          "Abbreviation": "RUTG",
          "Week": 12,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Penn State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-19T00:00:00-05:00"
        },
        {
          "FullName": "Penn State Nittany Lions",
          "Location": "Penn State",
          "Abbreviation": "PSU",
          "Week": 12,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Rutgers",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-19T00:00:00-05:00"
        },
        {
          "FullName": "Minnesota Golden Gophers",
          "Location": "Minnesota",
          "Abbreviation": "MINN",
          "Week": 12,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Iowa",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-19T00:00:00-05:00"
        },
        {
          "FullName": "Iowa Hawkeyes",
          "Location": "Iowa",
          "Abbreviation": "IOWA",
          "Week": 12,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Minnesota",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-19T00:00:00-05:00"
        },
        {
          "FullName": "Nebraska Cornhuskers",
          "Location": "Nebraska",
          "Abbreviation": "NEB",
          "Week": 12,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Wisconsin",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-19T00:00:00-05:00"
        },
        {
          "FullName": "Wisconsin Badgers",
          "Location": "Wisconsin",
          "Abbreviation": "WISC",
          "Week": 12,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Nebraska",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-19T00:00:00-05:00"
        },
        {
          "FullName": "Purdue Boilermakers",
          "Location": "Purdue",
          "Abbreviation": "PUR",
          "Week": 12,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Northwestern",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-19T00:00:00-05:00"
        },
        {
          "FullName": "Northwestern Wildcats",
          "Location": "Northwestern",
          "Abbreviation": "NU",
          "Week": 12,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Purdue",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-19T00:00:00-05:00"
        },
        {
          "FullName": "Michigan State Spartans",
          "Location": "Michigan State",
          "Abbreviation": "MSU",
          "Week": 12,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Indiana",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-19T00:00:00-05:00"
        },
        {
          "FullName": "Indiana Hoosiers",
          "Location": "Indiana",
          "Abbreviation": "IU",
          "Week": 12,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Michigan State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-19T00:00:00-05:00"
        }
      ]
    },
    {
      "WeekNum": 13,
      "StartDate": "2022-11-22T03:00:00-05:00",
      "EndDate": "2022-11-29T02:59:00-05:00",
      "Games": [
        {
          "FullName": "Iowa Hawkeyes",
          "Location": "Iowa",
          "Abbreviation": "IOWA",
          "Week": 13,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Nebraska",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-25T16:00:00-05:00"
        },
        {
          "FullName": "Nebraska Cornhuskers",
          "Location": "Nebraska",
          "Abbreviation": "NEB",
          "Week": 13,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Iowa",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-25T16:00:00-05:00"
        },
        {
          "FullName": "Penn State Nittany Lions",
          "Location": "Penn State",
          "Abbreviation": "PSU",
          "Week": 13,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Michigan State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-26T00:00:00-05:00"
        },
        {
          "FullName": "Michigan State Spartans",
          "Location": "Michigan State",
          "Abbreviation": "MSU",
          "Week": 13,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Penn State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-26T00:00:00-05:00"
        },
        {
          "FullName": "Wisconsin Badgers",
          "Location": "Wisconsin",
          "Abbreviation": "WISC",
          "Week": 13,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Minnesota",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-26T00:00:00-05:00"
        },
        {
          "FullName": "Minnesota Golden Gophers",
          "Location": "Minnesota",
          "Abbreviation": "MINN",
          "Week": 13,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Wisconsin",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-26T00:00:00-05:00"
        },
        {
          "FullName": "Northwestern Wildcats",
          "Location": "Northwestern",
          "Abbreviation": "NU",
          "Week": 13,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Illinois",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-26T00:00:00-05:00"
        },
        {
          "FullName": "Illinois Fighting Illini",
          "Location": "Illinois",
          "Abbreviation": "ILL",
          "Week": 13,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Northwestern",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-26T00:00:00-05:00"
        },
        {
          "FullName": "Indiana Hoosiers",
          "Location": "Indiana",
          "Abbreviation": "IU",
          "Week": 13,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Purdue",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-26T00:00:00-05:00"
        },
        {
          "FullName": "Purdue Boilermakers",
          "Location": "Purdue",
          "Abbreviation": "PUR",
          "Week": 13,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Indiana",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-26T00:00:00-05:00"
        },
        {
          "FullName": "Maryland Terrapins",
          "Location": "Maryland",
          "Abbreviation": "MD",
          "Week": 13,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Rutgers",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-26T00:00:00-05:00"
        },
        {
          "FullName": "Rutgers Scarlet Knights",
          "Location": "Rutgers",
          "Abbreviation": "RUTG",
          "Week": 13,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Maryland",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-26T00:00:00-05:00"
        },
        {
          "FullName": "Ohio State Buckeyes",
          "Location": "Ohio State",
          "Abbreviation": "OSU",
          "Week": 13,
          "Winner": false,
          "HomeTeam": true,
          "OpponentLocation": "Michigan",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-26T12:00:00-05:00"
        },
        {
          "FullName": "Michigan Wolverines",
          "Location": "Michigan",
          "Abbreviation": "MICH",
          "Week": 13,
          "Winner": false,
          "HomeTeam": false,
          "OpponentLocation": "Ohio State",
          "Score": "0-0",
          "IsBigTen": true,
          "IsCompleted": false,
          "GameDateTime": "2022-11-26T12:00:00-05:00"
        }
      ]
    }
  ],
  "UnmappedSelections": []
}